// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using data.validata.com.Context;

#nullable disable

namespace data.validata.com.Migrations
{
    [DbContext(typeof(ValidataDbContext))]
    [Migration("20250701112748_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Validata")
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("data.validata.com.Entities.OperationSource", b =>
                {
                    b.Property<int>("OperationSourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OperationSourceId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OperationSourceId");

                    b.ToTable("OperationSource", "Validata");

                    b.HasData(
                        new
                        {
                            OperationSourceId = 1,
                            Name = "Pre Defined"
                        },
                        new
                        {
                            OperationSourceId = 2,
                            Name = "Api"
                        },
                        new
                        {
                            OperationSourceId = 3,
                            Name = "Import"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
